AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 303
      Role: 'arn:aws:iam::690128978051:role/service-role/LF1-role-go4oal0b'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
      VpcConfig:
        SecurityGroupIds:
          - sg-0e945c51e04a2ae36
        SubnetIds:
          - subnet-e39cf085
      Layers:
        - 'arn:aws:lambda:us-east-1:690128978051:layer:libs:3'
